### ISSUE TITLE
Fix switch from burger menu to text

### ISSUE THREAD

**Issue by tomsiebring** [CollActionteam/collaction_website#70]
Burger menu switches into the full width text header too fast. As you can see on the image, the text is below the logo, which should not occur. 

On small width screens, the logo and burger are nicely located in the top left and right corner respectively. The desired behaviour is that, when the page width is sufficient to accommodate the logo and text at the same nicely located spot in the top left and right corner, the text appears. At the moment, as you can see in the image, the spacing on the left side of the logo is much bigger than on a small screen (same for right side). Desired behaviour is that left/right spacing from small screen is the first 'entry point' of the full text being visible.

<img width="794" alt="image" src="https://user-images.githubusercontent.com/38819098/220251323-736933df-ac5f-4adf-a8de-edc6d5d4c948.png">

<img width="664" alt="image" src="https://user-images.githubusercontent.com/38819098/220251357-d5d3f900-817e-4644-925b-e7e35a9bc6c4.png">

**Comment by adipginting** [comment]
Hi, Tom. The issue is on line 52 on the file NavBar.tsx (https://github.com/CollActionteam/collaction_website/blob/main/src/components/NavBar.tsx) specifically this code:
`px-6`. This code add 24 pixel horizontal padding that push the horizontal text to go down at breakpoint of medium devices. There are two solutions to this: the first is to reduce padding to 4px by editing the code to `px-1` and continue to use zero horizontal padding on medium device breakpoint. So the line could look like this:
`'flex flex-col md:flex-row flex-wrap px-1 lg:px-0 md:items-center justify-center md:justify-between mx-auto py-4',` or like this:
'flex flex-col md:flex-row flex-wrap px-1 md:px-0 md:items-center justify-center md:justify-between mx-auto py-4',
